//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARC_Final_Vision_Inspection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cameraIPAddress {
            get {
                return ((string)(this["cameraIPAddress"]));
            }
            set {
                this["cameraIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoButtonEnabled {
            get {
                return ((bool)(this["autoButtonEnabled"]));
            }
            set {
                this["autoButtonEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoButtonVisible {
            get {
                return ((bool)(this["autoButtonVisible"]));
            }
            set {
                this["autoButtonVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string autoButtonWriteAddress {
            get {
                return ((string)(this["autoButtonWriteAddress"]));
            }
            set {
                this["autoButtonWriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string autoButtonReadAddress {
            get {
                return ((string)(this["autoButtonReadAddress"]));
            }
            set {
                this["autoButtonReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton1Enabled {
            get {
                return ((bool)(this["plcButton1Enabled"]));
            }
            set {
                this["plcButton1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton1Visible {
            get {
                return ((bool)(this["plcButton1Visible"]));
            }
            set {
                this["plcButton1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton1WriteAddress {
            get {
                return ((string)(this["plcButton1WriteAddress"]));
            }
            set {
                this["plcButton1WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton1ReadAddress {
            get {
                return ((string)(this["plcButton1ReadAddress"]));
            }
            set {
                this["plcButton1ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton1OnLabel {
            get {
                return ((string)(this["plcButton1OnLabel"]));
            }
            set {
                this["plcButton1OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton1OffLabel {
            get {
                return ((string)(this["plcButton1OffLabel"]));
            }
            set {
                this["plcButton1OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton2Enabled {
            get {
                return ((bool)(this["plcButton2Enabled"]));
            }
            set {
                this["plcButton2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton2Visible {
            get {
                return ((bool)(this["plcButton2Visible"]));
            }
            set {
                this["plcButton2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton2WriteAddress {
            get {
                return ((string)(this["plcButton2WriteAddress"]));
            }
            set {
                this["plcButton2WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton2ReadAddress {
            get {
                return ((string)(this["plcButton2ReadAddress"]));
            }
            set {
                this["plcButton2ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton2OnLabel {
            get {
                return ((string)(this["plcButton2OnLabel"]));
            }
            set {
                this["plcButton2OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton2OffLabel {
            get {
                return ((string)(this["plcButton2OffLabel"]));
            }
            set {
                this["plcButton2OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton3Enabled {
            get {
                return ((bool)(this["plcButton3Enabled"]));
            }
            set {
                this["plcButton3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton3Visible {
            get {
                return ((bool)(this["plcButton3Visible"]));
            }
            set {
                this["plcButton3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton3WriteAddress {
            get {
                return ((string)(this["plcButton3WriteAddress"]));
            }
            set {
                this["plcButton3WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton3ReadAddress {
            get {
                return ((string)(this["plcButton3ReadAddress"]));
            }
            set {
                this["plcButton3ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton3OnLabel {
            get {
                return ((string)(this["plcButton3OnLabel"]));
            }
            set {
                this["plcButton3OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton3OffLabel {
            get {
                return ((string)(this["plcButton3OffLabel"]));
            }
            set {
                this["plcButton3OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton4Enabled {
            get {
                return ((bool)(this["plcButton4Enabled"]));
            }
            set {
                this["plcButton4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton4Visible {
            get {
                return ((bool)(this["plcButton4Visible"]));
            }
            set {
                this["plcButton4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton4WriteAddress {
            get {
                return ((string)(this["plcButton4WriteAddress"]));
            }
            set {
                this["plcButton4WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton4ReadAddress {
            get {
                return ((string)(this["plcButton4ReadAddress"]));
            }
            set {
                this["plcButton4ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton4OnLabel {
            get {
                return ((string)(this["plcButton4OnLabel"]));
            }
            set {
                this["plcButton4OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton4OffLabel {
            get {
                return ((string)(this["plcButton4OffLabel"]));
            }
            set {
                this["plcButton4OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton5Enabled {
            get {
                return ((bool)(this["plcButton5Enabled"]));
            }
            set {
                this["plcButton5Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton5Visible {
            get {
                return ((bool)(this["plcButton5Visible"]));
            }
            set {
                this["plcButton5Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton5WriteAddress {
            get {
                return ((string)(this["plcButton5WriteAddress"]));
            }
            set {
                this["plcButton5WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton5ReadAddress {
            get {
                return ((string)(this["plcButton5ReadAddress"]));
            }
            set {
                this["plcButton5ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton5OnLabel {
            get {
                return ((string)(this["plcButton5OnLabel"]));
            }
            set {
                this["plcButton5OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton5OffLabel {
            get {
                return ((string)(this["plcButton5OffLabel"]));
            }
            set {
                this["plcButton5OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton6Enabled {
            get {
                return ((bool)(this["plcButton6Enabled"]));
            }
            set {
                this["plcButton6Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcButton6Visible {
            get {
                return ((bool)(this["plcButton6Visible"]));
            }
            set {
                this["plcButton6Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton6WriteAddress {
            get {
                return ((string)(this["plcButton6WriteAddress"]));
            }
            set {
                this["plcButton6WriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton6ReadAddress {
            get {
                return ((string)(this["plcButton6ReadAddress"]));
            }
            set {
                this["plcButton6ReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton6OnLabel {
            get {
                return ((string)(this["plcButton6OnLabel"]));
            }
            set {
                this["plcButton6OnLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcButton6OffLabel {
            get {
                return ((string)(this["plcButton6OffLabel"]));
            }
            set {
                this["plcButton6OffLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string manualButtonWriteAddress {
            get {
                return ((string)(this["manualButtonWriteAddress"]));
            }
            set {
                this["manualButtonWriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string manualButtonReadAddress {
            get {
                return ((string)(this["manualButtonReadAddress"]));
            }
            set {
                this["manualButtonReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcCommsEnabled {
            get {
                return ((bool)(this["plcCommsEnabled"]));
            }
            set {
                this["plcCommsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcIPAddress {
            get {
                return ((string)(this["plcIPAddress"]));
            }
            set {
                this["plcIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcMessageDisplayColorIndicatorAddress {
            get {
                return ((string)(this["plcMessageDisplayColorIndicatorAddress"]));
            }
            set {
                this["plcMessageDisplayColorIndicatorAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcMessageDisplayAddress {
            get {
                return ((string)(this["plcMessageDisplayAddress"]));
            }
            set {
                this["plcMessageDisplayAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcPartCountersEnabled {
            get {
                return ((bool)(this["plcPartCountersEnabled"]));
            }
            set {
                this["plcPartCountersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcPartCounterGoodAddress {
            get {
                return ((string)(this["plcPartCounterGoodAddress"]));
            }
            set {
                this["plcPartCounterGoodAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcPartCounterBadAddress {
            get {
                return ((string)(this["plcPartCounterBadAddress"]));
            }
            set {
                this["plcPartCounterBadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcResultMonitorEnabled {
            get {
                return ((bool)(this["plcResultMonitorEnabled"]));
            }
            set {
                this["plcResultMonitorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResultMonitorName {
            get {
                return ((string)(this["plcResultMonitorName"]));
            }
            set {
                this["plcResultMonitorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult1Address {
            get {
                return ((string)(this["plcResult1Address"]));
            }
            set {
                this["plcResult1Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult1Title {
            get {
                return ((string)(this["plcResult1Title"]));
            }
            set {
                this["plcResult1Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult2Address {
            get {
                return ((string)(this["plcResult2Address"]));
            }
            set {
                this["plcResult2Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult2Title {
            get {
                return ((string)(this["plcResult2Title"]));
            }
            set {
                this["plcResult2Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult3Address {
            get {
                return ((string)(this["plcResult3Address"]));
            }
            set {
                this["plcResult3Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcResult3Title {
            get {
                return ((string)(this["plcResult3Title"]));
            }
            set {
                this["plcResult3Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryMessageAddress {
            get {
                return ((string)(this["plcSecondaryMessageAddress"]));
            }
            set {
                this["plcSecondaryMessageAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryMessageColorAddress {
            get {
                return ((string)(this["plcSecondaryMessageColorAddress"]));
            }
            set {
                this["plcSecondaryMessageColorAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcMainPartCounterResetButtonAddress {
            get {
                return ((string)(this["plcMainPartCounterResetButtonAddress"]));
            }
            set {
                this["plcMainPartCounterResetButtonAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryPartCounterResetButtonAddress {
            get {
                return ((string)(this["plcSecondaryPartCounterResetButtonAddress"]));
            }
            set {
                this["plcSecondaryPartCounterResetButtonAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcSecondaryDisplayMessageEnabled {
            get {
                return ((bool)(this["plcSecondaryDisplayMessageEnabled"]));
            }
            set {
                this["plcSecondaryDisplayMessageEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mainMessageTitle {
            get {
                return ((string)(this["mainMessageTitle"]));
            }
            set {
                this["mainMessageTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string secondaryMessageTitle {
            get {
                return ((string)(this["secondaryMessageTitle"]));
            }
            set {
                this["secondaryMessageTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcSecondaryPartCounterEnabled {
            get {
                return ((bool)(this["plcSecondaryPartCounterEnabled"]));
            }
            set {
                this["plcSecondaryPartCounterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryPartCounterGoodAddress {
            get {
                return ((string)(this["plcSecondaryPartCounterGoodAddress"]));
            }
            set {
                this["plcSecondaryPartCounterGoodAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryPartCounterBadAddress {
            get {
                return ((string)(this["plcSecondaryPartCounterBadAddress"]));
            }
            set {
                this["plcSecondaryPartCounterBadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcMainSerialNumberAddress {
            get {
                return ((string)(this["plcMainSerialNumberAddress"]));
            }
            set {
                this["plcMainSerialNumberAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondarySerialNumberAddress {
            get {
                return ((string)(this["plcSecondarySerialNumberAddress"]));
            }
            set {
                this["plcSecondarySerialNumberAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryResult1Address {
            get {
                return ((string)(this["plcSecondaryResult1Address"]));
            }
            set {
                this["plcSecondaryResult1Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryResult2Address {
            get {
                return ((string)(this["plcSecondaryResult2Address"]));
            }
            set {
                this["plcSecondaryResult2Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plcSecondaryResult3Address {
            get {
                return ((string)(this["plcSecondaryResult3Address"]));
            }
            set {
                this["plcSecondaryResult3Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plcSecondaryResultEnabled {
            get {
                return ((bool)(this["plcSecondaryResultEnabled"]));
            }
            set {
                this["plcSecondaryResultEnabled"] = value;
            }
        }
    }
}
